# =========================================================
# CONFIGURAÇÃO DE CONEXÃO COM O BANCO DE DADOS (SUPABASE)
# =========================================================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.htfmcqtguiwjwoovippz
spring.datasource.password=TUE2Sq1WgSd6WE7l
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# =========================================================
# Define o dialeto específico do PostgreSQL para geração correta do SQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Atualiza e cria as tabelas automaticamente no banco Supabase com base nas tuas @Entity
spring.jpa.hibernate.ddl-auto=update

# Exibe as consultas SQL executadas no console (útil para testes)
spring.jpa.show-sql=true

# Formata o código SQL no console para facilitar a leitura
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# CONFIGURAÇÃO DO SERVIDOR WEB (TOMCAT)
# =========================================================
# Usa a porta fornecida pelo servidor de hospedagem ou 8080 por padrão localmente
server.port=${PORT:10000}